name: Zion.Common + Pack + Push no NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-push:
    env:
      PROJECT_PATH: ./Zion.Common/Zion.Common.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Zion.Common
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Packet generator
      run: dotnet pack ${{ env.PROJECT_PATH }} -c Release -o out

    - name: Push to NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
